#!/usr/bin/python3

import sys
import subprocess

if len(sys.argv) > 1 and sys.argv[1] == "config":
  graph_args = "-A -X 0 -L 3"

  print('multigraph sensors_wohnzimmer')
  sys.stdout.buffer.write('graph_vlabel °C\n'.encode('latin-1'))
  print('graph_category thermal')
  print('graph_title Room Temperature Wohnzimmer')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer.label Wohnzimmer')
  print('wohnzimmer.critical 50')

  print('multigraph sensors_wohnzimmer_flow')
  sys.stdout.buffer.write('graph_vlabel °C/h\n'.encode('latin-1'))
  print('graph_title Room Thermal Flow')
  print('graph_category thermal')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer-flow.label Wohnzimmer')

  print('multigraph sensors_wohnzimmer_stats')
  print('graph_title Temperature Sensor Readout Error Rate')
  print('graph_category thermal')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer-ratio.label Wohnzimmer')

  print('multigraph sensors_wohnzimmer_heizung')
  sys.stdout.buffer.write('graph_vlabel °C\n'.encode('latin-1'))
  print('graph_category thermal')
  print('graph_title Temperatur Heizung')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer-heizung.label Heizung Wohnzimmer')
  print('wohnzimmer-heizung.critical 100')

  print('multigraph sensors_wohnzimmer_heizung_flow')
  sys.stdout.buffer.write('graph_vlabel °C/h\n'.encode('latin-1'))
  print('graph_title Heizung Thermal Flow')
  print('graph_category thermal')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer-heizung-flow.label Heizung Wohnzimmer')

  print('multigraph sensors_wohnzimmer_heizung_stats')
  print('graph_title Temperature Sensor Readout Error Rate')
  print('graph_category thermal')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer-heizung-ratio.label Heizung Wohnzimmer')

  print('multigraph sensors')
  sys.stdout.buffer.write('graph_vlabel °C\n'.encode('latin-1'))
  print('graph_category thermal')
  print('graph_title Room Temperature')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer.label Wohnzimmer')
  print('wohnzimmer.critical 50')
  print('wohnzimmer-heizung.label Heizung Wohnzimmer')
  print('wohnzimmer-heizung.critical 100')

  print('multigraph sensors_flow')
  sys.stdout.buffer.write('graph_vlabel °C/h\n'.encode('latin-1'))
  print('graph_title Room Thermal Flow')
  print('graph_category thermal')
  print('graph_args {}'.format(graph_args))
  print('wohnzimmer-flow.label Wohnzimmer')
  print('wohnzimmer-heizung-flow.label Heizung Wohnzimmer')
  sys.exit()

print(subprocess.check_output(["/bin/nc", "-w", "1", "127.0.0.1", "31338"]).decode())
